language: node_js
node_js:
  - 14
  - 16
  - 18
services:
  - postgresql
  - redis-server
before_script:
  - psql -f db/install.sql -U postgres
  - PGPASSWORD=marcus psql -d application -f db/structure.sql -U marcus
  - PGPASSWORD=marcus psql -d application -f db/data.sql -U marcus
script:
  - npm test
